# Generated by Django 3.1.2 on 2020-10-23 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ticketswap", "0002_university_domain_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="university",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ticketswap.university",
            ),
        ),
    ]
