# Generated by Django 3.1.2 on 2020-11-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketswap', '0007_auto_20201102_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
