# Generated by Django 3.1.2 on 2020-11-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketswap', '0008_auto_20201102_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
