# Generated by Django 3.1.2 on 2020-11-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketswap', '0009_auto_20201102_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='venmo',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
