# Generated by Django 3.1.2 on 2020-11-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketswap', '0011_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
