# Generated by Django 3.1.2 on 2020-11-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketswap', '0012_auto_20201119_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
